<?php

/**
 * @file
 * 
 * This module provides a smart naviagtion box as a block or ctools plugin.
 */

// Constants
define('DING_NAV_BOX_PATH', drupal_get_path('module', 'ding_navigation_box'));

/**
 * Implements hook_block_info().
 */
function ding_navigation_box_block_info() {
  $blocks = array();
  $blocks['ding_navigation_box'] = array(
    'info' => t('Ding navigation box'),  
  );
  return $blocks;
}

/**
 * Implements hook_block_view().
 * 
 * Ignoring $delta since we only have 1 block.
 */
function ding_navigation_box_block_view($delta) {
  $block = array();
  $block['subject'] = t('Ding navigation box');
  // The navigation box consist of entries wich each consist of a navigation 
  // item and a content area. Below we fetch the entries, split them up in items
  // and areas and pass these as render arrays to the navigation box template.
  $entries = _ding_navigation_box_get_entries();
  $block['content'] = array(
    '#theme' => 'ding_navigation_box',
      'navigation_items' => $entries['navigation_items'],
      'content_areas' => $entries['content_areas'],
  );
  return $block;
}

/**
 * Implements hook_theme().
 * 
 * Declares the theme hooks that renders the Ding navigation box.
 */
function ding_navigation_box_theme() {
  return array(
    'ding_navigation_box' => array(
      'render element' => 'element',
      'template' => 'ding-navigation-box',
      'path' => DING_NAV_BOX_PATH . '/templates',
    ),
    'ding_navigation_box_item' => array(
      'variables' => array(
        'entry_title' => 'Default text',
        'entry_position' => -1,  
      ),
      'template' => 'ding-navigation-box-item',
      'path' => DING_NAV_BOX_PATH . '/templates',  
    ),
    'ding_navigation_box_content_area' => array(
      'variables' => array(
        'entry_content' => '',
        'entry_position' => -1,  
      ),
      'template' => 'ding-navigation-box-content-area',
      'path' => DING_NAV_BOX_PATH . '/templates',   
    ),  
  );
}

/**
 * Module template preprocess funtion for the navigation box.
 */
function template_preprocess_ding_navigation_box(&$variables) {
  $element = $variables['element'];
  // If there's no items or content areas present dont render entries at all. 
  if (empty($element['navigation_items'])) {
    $variables['navigation_items'] = $variables['content_areas'] = FALSE;
  }
  // Else we setup the variables for the navigation box template and add the 
  // necessary javascript and css files.
  else {
    $variables['navigation_items'] = $element['navigation_items'];
    $variables['content_areas'] = $element['content_areas'];
    _ding_navigation_box_add_css();
    _ding_navigation_box_add_javascript();
  }
}

/**
 * Wrapper function for adding javascript.
 */
function _ding_navigation_box_add_javascript() {
  
}

/**
 * Wrapper function for adding css
 */
function _ding_navigation_box_add_css() {
  $css_options = array(
    'type' => 'file',
    'group' => CSS_DEFAULT,
  );
  drupal_add_css(DING_NAV_BOX_PATH . '/css/ding-navigation-box.css', $css_options);
}


/**
 * Return an array with the entries for the navigation box setup as 
 * render-arrays.
 * 
 * @return 
 * array(navigation_items => content_areas)
 */
function _ding_navigation_box_get_entries() {
  $entries = array();
  $entries['navigation_items'][] = array(
    '#theme' => 'ding_navigation_box_item',
    '#entry_title' => 'Test 1',
    '#entry_position' => 1,  
  );
  $entries['navigation_items'][] = array(
    '#theme' => 'ding_navigation_box_item',
    '#entry_title' => 'Test 2',
    '#entry_position' => 2,
  );
  $entries['navigation_items'][] = array(
    '#theme' => 'ding_navigation_box_item',
    '#entry_title' => 'Test 3',
    '#entry_position' => 3,  
  );
  $entries['navigation_items'][] = array(
    '#theme' => 'ding_navigation_box_item',
    '#entry_title' => 'Test 4',
    '#entry_position' => 4,  
  );
  $entries['navigation_items'][] = array(
    '#theme' => 'ding_navigation_box_item',
    '#entry_title' => 'Test 5',
    '#entry_position' => 5,  
  );  
  $entries['content_areas'][] = array(
    '#theme' => 'ding_navigation_box_content_area',
    '#entry_content' => array(
      '#markup' => '<p>This is test area 1</p>',  
    ),
    '#entry_position' => 1,  
  );
  $entries['content_areas'][] = array(
    '#theme' => 'ding_navigation_box_content_area',
    '#entry_content' => array(
      '#markup' => '<p>This is test area 2</p>',  
    ),
    '#entry_position' => 2,  
  );
  $entries['content_areas'][] = array(
    '#theme' => 'ding_navigation_box_content_area',
    '#entry_content' => array(
      '#markup' => '<p>This is test area 3</p>',  
    ),
    '#entry_position' => 3,  
  );
  $entries['content_areas'][] = array(
    '#theme' => 'ding_navigation_box_content_area',
    '#entry_content' => array(
      '#markup' => '<p>This is test area 4</p>',  
    ),
    '#entry_position' => 4,  
  );
  $entries['content_areas'][] = array(
    '#theme' => 'ding_navigation_box_content_area',
    '#entry_content' => array(
      '#markup' => '<p>This is test area 5</p>',  
    ),
    '#entry_position' => 5,  
  );  
  return $entries;
}